#!/bin/bash

~/.local/share/distrobox/distrotunnel/scripts/dmt --noconfirm -a \
        atuin \
        bat \
        chezmoi \
        curl \
        dust \
        exa \
        fd \
        fzf \
        gitflow-avh \
        htop \
        flameshot \
        taskwarrior-tui \
        timew \
        firefox-developer-edition \
        neovim \
        openssh \
        ripgrep \
        starship \
        neofetch \
        tmux \
        tmuxp \
        xclip \
        yarn \
        ; sudo pacman -Rns $(pacman -Qtdq) \
        ; sudo pacman -Scc --noconfirm \
        ; sudo rm -Rf /var/cache/pacman/pkg/*.

distrobox-export -b ~/.local/share/distrobox/distrotunnel/scripts/dmt -ep ~/.local/share/distrobox/distrotunnel/bin 
distrobox-export -b ~/.local/share/distrobox/distrotunnel/scripts/won -ep ~/.local/share/distrobox/distrotunnel/bin 
